---
title: "Title"
author: 'Author One ^1,✉^, Author Two ^1^'
css: "production.css"
abstract: |
  | [STROBE 1.a] Indicate the study’s design with a commonly used term in the title or the abstract
  |
  | [STROBE 1.b] Provide in the abstract an informative and balanced summary of what was done and what was found
  |
  | [RECORD 1.1] The type of data used should be specified in the title or abstract. When possible, the name of the databases used should be included.
  |
  | [RECORD 1.2] If applicable, the geographic region and timeframe within which the study took place should be reported in the title or abstract.
  |
  | [RECORD 1.3] If linkage between databases was conducted for the study, this should be clearly stated in the title or abstract.

documentclass: article
description: 'Manuscript'
clean: false
bibliography: efi_paper.bib
csl: harvard-cite-them-right.csl
output:
  bookdown::html_document2:
    fig_caption: true
    self_contained: true
    number_sections: false
    keep_md: true
    clean: false
  bookdown::word_document2:
    reference_docx: efi_template.docx
    fig_caption: true
    self_contained: true
    keep_md: true
    number_sections: false
---

```{r load_deps, echo=FALSE, message=FALSE, warning=FALSE,results='hide'}
.projpackages <- c('GGally','pander','dplyr','ggplot2','data.table'
                   ,'survival','broom','forcats','table1','english','bookdown');
.deps <- c( 'analysis.R' );
.debug <- 0;
message(paste0('\n\n working dir: ',getwd(),'\n\n'));
cat('\n\nAvailable Files:',list.files(),sep='\n','\n');
.junk<-capture.output(source(file.path('./scripts/global.R'),chdir=TRUE,echo=!1
                             ,local=TRUE));
# Set some formatting options for this document
panderOptions('table.alignment.default','right');
panderOptions('table.alignment.rownames','right');
panderOptions('table.split.table',Inf);
panderOptions('p.wrap','');
panderOptions('p.copula',', and ');
panderOptions('graph.fontfamily','serif');
# theme_get() gives default theme
theme_set(theme_bw(base_family = 'serif',base_size=14) +
            theme(strip.background = element_rect(fill=NA,color=NA)
                  ,strip.text = element_text(size=15)));
knitr::opts_chunk$set(echo=.debug>0, warning=.debug>0, message=.debug>0);

# detect current output format
.outfmt <- knitr::opts_knit$get('rmarkdown.pandoc.to');
if(is.null(.outfmt)){
  .outfmt <- if(knitr::is_html_output()) 'html' else {
    if(knitr::is_latex_output()) 'latex' else {
      if(interactive()) 'html' else {
        'unknown';
    }}}};
message('.outfmt = ',.outfmt);

.currentscript <- current_scriptname('efi_patientsafety.Rmd');
.outcomenames <- c('vi_c_psi','vi_c_hospinfect','vi_c_hosptrauma'
                   ,'vi_c_cardiac');
snip_outcomes <- rname(.outcomenames);

# limit the data to items of interest


# snippets ----

```
# Introduction/Background

## Background Rationale 

[Strobe 2] Explain the scientific background and rationale for the investigation being reported

## Objectives 
[Strobe 3] State specific objectives, including any prespecified hypotheses

# Methods

## Study Design

[Strobe 4] Present key elements of study design early in the paper

## Setting

[Strobe 5] Describe the setting, locations, and relevant dates, including periods of recruitment, exposure, follow-up, and data collection

## Participants


[Strobe 6.a] 

* Cohort study - Give the eligibility criteria, and the sources and methods of selection of participants. Describe methods of follow-up
* Case-control study - Give the eligibility criteria, and the sources and methods of case ascertainment and control selection. Give the rationale for the choice of cases and controls
* Cross-sectional study - Give the eligibility criteria, and the sources and methods of selection of participants

[Strobe 6.b]

* Cohort study - For matched studies, give matching criteria and number of exposed and unexposed
* Case-control study - For matched studies, give matching criteria and the number of controls per case

[RECORD 6.1] The methods of study population selection (such as codes or algorithms used to identify subjects) should be listed in detail. If this is not possible, an explanation should be provided. 

[RECORD 6.2] Any validation studies of the codes or algorithms used to select the population should be referenced. If validation was conducted for this study and not published elsewhere, detailed methods and results should be provided.

[RECORD 6.3] If the study involved linkage of databases, consider use of a flow diagram or other graphical display to demonstrate the data linkage process, including the number of individuals with linked data at each stage.

## Variables

[Strobe 7] Clearly define all outcomes, exposures, predictors, potential confounders, and effect modifiers. Give diagnostic criteria, if applicable.

[RECORD 7.1] A complete list of codes and algorithms used to classify exposures, outcomes, confounders, and effect modifiers should be provided. If these cannot be reported, an explanation should be provided.

## Data sources/ measurement

[Strobe 8] For each variable of interest, give sources of data and details of methods of assessment (measurement). Describe comparability of assessment methods if there is more than one group

## Bias
[Strobe 9] Describe any efforts to address potential sources of bias

## Study size

[Strobe 10] Explain how the study size was arrived at

## Quantitative variables

[Strobe 11] Explain how quantitative variables were handled in the analyses. If applicable, describe which groupings were chosen, and why

## Statistical methods

[Strobe 12.a] Describe all statistical methods, including those used to control for confounding

[Strobe 12.b] Describe any methods used to examine subgroups and interactions

[Strobe 12.c] Explain how missing data were addressed

[Strobe 12.d] 

* Cohort study - If applicable, explain how loss to follow-up was addressed
* Case-control study - If applicable, explain how matching of cases and controls was addressed
* Cross-sectional study - If applicable, describe analytical methods taking account of sampling strategy

[Strobe 12.e] Describe any sensitivity analyses
Data access and cleaning methods

## Data access and cleaning methods

[RECORD 12.1] Authors should describe the extent to which the investigators had access to the database population used to create the study population.

[RECORD 12.2] Authors should provide information on the data cleaning methods used in the study.

## Linkage

[RECORD 12.3] State whether the study included person-level, institutional-level, or other data linkage across two or more databases. The methods of linkage and methods of linkage quality evaluation should be provided.

# Results

## Participants

[STROBE 13.a] Report the numbers of individuals at each stage of the study (e.g., numbers potentially eligible, examined for eligibility, confirmed eligible, included in the study, completing follow-up, and analysed)

[STROBE 13.b] Give reasons for non-participation at each stage.

[STROBE 13.c] Consider use of a flow diagram

[RECORD 13.1] Describe in detail the selection of the persons included in the study (i.e., study population selection) including filtering based on data quality, data availability and linkage. The selection of included persons can be described in the text and/or by means of the study flow diagram.

## Descriptive data

[STROBE 14.a] Give characteristics of study participants (e.g., demographic, clinical, social) and information on exposures and potential confounders

[STROBE 14.b]  Indicate the number of participants with missing data for each variable of interest

[STROBE 14.c]

* Cohort study - summarise follow-up time (e.g., average and total amount)

## Outcome data

[STROBE 15]

* Cohort study - Report numbers of outcome events or summary measures over time
* Case-control study - Report numbers in each exposure category, or summary measures of exposure
* Cross-sectional study - Report numbers of outcome events or summary measures

## Main results
[STROBE 16.a] Give unadjusted estimates and, if applicable, confounder-adjusted estimates and their precision (e.g., 95% confidence interval). Make clear which confounders were adjusted for and why they were included
[STROBE 16.b] Report category boundaries when continuous variables were categorized
[STROBE 16.c] If relevant, consider translating estimates of relative risk into absolute risk for a meaningful time period

## Other analyses

[STROBE 17] Report other analyses done—e.g., analyses of subgroups and interactions, and sensitivity analyses


# Discussion

## Key results

[STROBE 18] Summarise key results with reference to study objectives

## Limitations

[STROBE 19] Discuss limitations of the study, taking into account sources of potential bias or imprecision. Discuss both direction and magnitude of any potential bias

[RECORD 19.1] Discuss the implications of using data that were not created or collected to answer the specific research question(s). Include discussion of misclassification bias, unmeasured confounding, missing data, and changing eligibility over time, as they pertain to the study being reported.

## Interpretation

[STROBE 20] Give a cautious overall interpretation of results considering objectives, limitations, multiplicity of analyses, results from similar studies, and other relevant evidence

## Generalisability

[STROBE 21]
Discuss the generalisability (external validity) of the study results

# Conclusions

[RECORD 22.1] Authors should provide information on how to access any supplemental information such as the study protocol, raw data, or programming code.

# Acknowledgments

[STROBE 22] Give the source of funding and the role of the funders for the present study and, if applicable, for the original study on which the present article is based

# References



---
date: '2021-08-08'

---
