on: push
name: Render Manuscript

jobs:
  render:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          #- {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          #- {os: ubuntu-20.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          #- {os: windows-latest, r: 'release'}
          #- {os: macOS-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.CI_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libcurl on linux
        run: sudo apt-get install libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes",repos='https://cloud.r-project.org')
          install.packages("bookdown",repos='https://cloud.r-project.org')
          cat('\n\nDone install.packages\n\n')
          remotes::install_cran("rmarkdown")
          cat('\n\nDone install_cran\n\n')
          remotes::install_github('bokov/rio')
          cat('\n\nDone rio\n\n')
          remotes::install_github('bokov/tidbits')
          cat('\n\nDone tidbits\n\n')
          cat('\n\nDone Package Installs\n\n')
        shell: Rscript {0}

      - name: Install submodules
        run: ./initgitmods.sh
        shell: bash

      - name: Debug via tmate
        if: runner.os == 'Linux'
        uses: csexton/debugger-action@master
        #uses: mxschmitt/action-tmate@v3

      - name: Render Files
        run: Rscript -e 'rmarkdown::render(file.path(".","efi_patientsafety.Rmd"))'
